name: synonym_valley
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.6
  flutter_swipable: ^1.1.0
  swipable_stack: ^0.6.2
  loading_indicator: ^3.0.1
  flutter_colorpicker: ^0.6.0
  fluttermoji: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icon/icon.png
    - assets/data/a.json    
    - assets/data/b.json   
    - assets/data/c.json   
    - assets/data/d.json   
    - assets/data/e.json   
    - assets/data/f.json   
    - assets/data/g.json   
    - assets/data/h.json   
    - assets/data/i.json  
    - assets/data/j.json  
    - assets/data/k.json   
    - assets/data/l.json   
    - assets/data/m.json   
    - assets/data/n.json   
    - assets/data/n.json   
    - assets/data/o.json   
    - assets/data/p.json   
    - assets/data/q.json   
    - assets/data/r.json   
    - assets/data/s.json   
    - assets/data/t.json   
    - assets/data/u.json   
    - assets/data/v.json   
    - assets/data/w.json   
    - assets/data/x.json   
    - assets/data/y.json   
    - assets/data/z.json   
